### ISSUE TITLE
function replace_relative_URI does not work for no protocol external link

### ISSUE THREAD

**Issue by takaTech** [yukihiko-shinoda/staticpress#9]
It does not work for no protocol external link like //fonts.googleapis.com.
You should fix regex in function replace_relative_URI like
```
		$pattern  = array(
			'# (href|src|action)="(/[^/"]*)"#ism',
			"# (href|src|action)='(/[^/']*)'#ism",
```
https://github.com/yukihiko-shinoda/staticpress/blob/master/includes/class-static_press.php#L500-L501

It works well on my wordpress.

**Comment by chrome-cgi** [comment]
The pattern above excludes any absolute path containing slashes, such as `/foo/bar.html`.
So the pattern should be like this:
```
		$pattern  = array(
			'# (href|src|srcset|action)="(/[^/][^"]*)"#ism',
			"# (href|src|srcset|action)='(/[^/][^']*)'#ism",
		);
```
I too found the same issue and fixed on my branch before in https://github.com/chrome-cgi/staticpress/commit/9f19509a340a0dddcdae7676d716c13802619f26

**Comment by yukihiko-shinoda** [comment]
I deployed new version 0.5.0 including [support no protocol external link](https://github.com/yukihiko-shinoda/staticpress/commit/6514bafcef484445eb66c8e140a60c1188cc2f52).
When there are still any inconvenience, please open this issue again.
